services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile.api
    container_name: aura_api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs                  
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 60s

  ui:
    build:
      context: .
      dockerfile: docker/ui/Dockerfile.ui
    container_name: aura_ui
    env_file: .env
    environment:
      AURA_API_URL: "http://api:8000"
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_healthy